### ISSUE TITLE
Englische Version

### ISSUE THREAD

**Issue by RexZetronYT23** [supercrafter333/theSpawn#1]
Ich könnte helfen bei der Englischen Version

**Comment by supercrafter333** [comment]
Ich habe die Naricht beim Teleport zur Lobby vergessen, ich werde sie aber noch hinzufügen. Bitte implementiere auch die neue Config und die gefixte datei, in die englische version :)

**Comment by supercrafter333** [comment]
Ich mache lieber Custom messages sorry
