### ISSUE TITLE
the plugin crashes when we respawn on the server...

### ISSUE THREAD

**Issue by Willtom999** [supercrafter333/theSpawn#10]
# Bug: [Bug Name]

### Informations
PTimeUI Version: [1.0.1]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [8.0.2]
PocketMine-MP Version: [3.17.5]

### Error
[Console Error:]

### readjustment instructions
[I've done...]
[1. ...]
[2. ...]
[3. ...]

### fix suggestions [optional]
[Your suggestion]

**Comment by supercrafter333** [comment]
Invalid. Please open a avlid Bug-Issue.

**Comment by Willtom999** [comment]
The bug is respawn the spawn
