### ISSUE TITLE
[Suggestion] Remove Prefix

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [supercrafter333/theSpawn#11]
**Is your feature request related to a problem? Please describe.**
I FREAKING HATE THE PREFIX! THE COLOR CODING OF IT IS TERRIBLE AND IS VERY ANNOYING

**Describe the solution you'd like**
Remove it or add an option to change it!

**Describe alternatives you've considered**
Removing it via DevTools! Until I releasized, I could have just annoyed a certified(ish) dev

**Additional context**
No

**Comment by supercrafter333** [comment]
I'll release a nee version with a Feature to change the Prefix in one or two days.

**Comment by supercrafter333** [comment]
Done in V1.2.5
