### ISSUE TITLE
[Suggestion] Add configold.yml on Update

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [supercrafter333/theSpawn#15]
**Is your feature request related to a problem? Please describe.**
So when I updated to the newest version of theSpawn, I was mad when I had to redo all of messages.yml! So after that I finished that, I am here now!

**Describe the solution you'd like**
I noticed that SimpleNPC, another plugin I had to update, renamed the config.yml so I can see what changed and fix it.
So make it rename messages.yml and config.yml to (name)old.yml

**Describe alternatives you've considered**
I guess just renaming them before updates

**Additional context**
No u

**Comment by supercrafter333** [comment]
I'll add it in a sooner Version! Thank you :)

**Comment by supercrafter333** [comment]
Done in V1.3.1!
