### ISSUE TITLE
[BUG:] Description...

### ISSUE THREAD

**Issue by NeeL-YT** [supercrafter333/theSpawn#16]
# Bug: [Internal Server Error]

### Informations
theSpawn Version: [1.0.1]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [7.4.13]
PocketMine-MP Version: [3.19.1]

### Error
[Console Error:
You haven't set up the hub 
How the heck i will set hub if i can't join]

### readjustment instructions
[I've done...]
[1. ...]
[2. ...]
[3. ...]

### fix suggestions [optional]
[Your suggestion]

**Comment by supercrafter333** [comment]
You're using an old Version of theSpawn.
