### ISSUE TITLE
[BUG:] Description...

### ISSUE THREAD

**Issue by GamilinoMC** [supercrafter333/theSpawn#17]
I installed the **TheSpawn** Plugin in my Server, but every time I try to join there stays **_Internal Server Error_**

In the Console stays First set a hub, but I only can set a hub if I'm on the Server.

**Comment by supercrafter333** [comment]
this warning is wanted, because theSpawn needs a hub. Please join to your server and set a hub or disable hub teleport in your config and try to join again. Good luck.
