### ISSUE TITLE
[Suggestion:] suggestion add Spawn Command the delay

### ISSUE THREAD

**Issue by Willtom999** [supercrafter333/theSpawn#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Willtom999** [comment]
Plz add is delay the command /spawn

**Comment by supercrafter333** [comment]
Great Idea!

**Comment by supercrafter333** [comment]
Do you mean a delay/cooldown for the command or a move delay?

**Comment by supercrafter333** [comment]
ANSWER!!! Or I'll close the Issue.

**Comment by Willtom999** [comment]
Is delay no cooldown

**Comment by supercrafter333** [comment]
Added to V1.4.0-DEV (V1.4.0 will release soon)!
