### ISSUE TITLE
[Suggestion] Permission Warps

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [supercrafter333/theSpawn#19]
**Is your feature request related to a problem? Please describe.**
No, not really.

**Describe the solution you'd like**
So when you enter the permission, theSpawn.warp.x, it'll let you have access to /warp x. You can make the perm anything you want and x is changeable to fit with the warp name.

**Describe alternatives you've considered**
Idk

**Additional context**
No

**Comment by supercrafter333** [comment]
Gr8 Idea

**Comment by supercrafter333** [comment]
Done in V1.5.0-Dev! Thanks you!
