### ISSUE TITLE
[BUG:] Internal Server Error when i respawn

### ISSUE THREAD

**Issue by DPG896** [supercrafter333/theSpawn#20]
![Screenshot_20210803-120029](https://user-images.githubusercontent.com/82310008/127955654-3c64d205-205b-4c4c-96ab-d61e84399ecb.png)
![Screenshot_20210803-120034](https://user-images.githubusercontent.com/82310008/127955661-7f7ba239-f15f-4ae7-9d00-7097ca90e1f3.png)
![Screenshot_20210803-120041](https://user-images.githubusercontent.com/82310008/127955668-6ae81e1b-b89d-4f32-9237-4e7301b1db14.png)
![Screenshot_20210803-120048](https://user-images.githubusercontent.com/82310008/127955675-a5dcfa56-a0c7-42fc-8a52-e186770bc24a.png)
This is the codes

**Comment by DPG896** [comment]
![Screenshot_20210803-120020](https://user-images.githubusercontent.com/82310008/127955752-3d8f9adf-a480-4422-9e79-626cd0984db4.png)
I forgot the 1st page

**Comment by supercrafter333** [comment]
I cannot see enough and therefore cannot help. This bug has not yet been confirmed.

**Comment by supercrafter333** [comment]
What version of PocketMine-MP and theSpawn do you use?

**Comment by DPG896** [comment]
The latest versions

**Comment by DPG896** [comment]
Plugin : 1.3.3

Pmmp version: 3.22.1

**Comment by DPG896** [comment]
I think we have a same issue [here](https://github.com/supercrafter333/theSpawn/issues/10)

**Comment by supercrafter333** [comment]
This will be fixed in V1.4. Thanks for reporting.

**Comment by DPG896** [comment]
Thano you :)

**Comment by supercrafter333** [comment]
Closed via commit [8fb71d4](https://github.com/supercrafter333/theSpawn/commit/8fb71d496e7590ab017186920c3c7be4115d9324)
