### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by llPushkarSinghll** [supercrafter333/theSpawn#22]
Add UI Or GUI in warp

**Comment by supercrafter333** [comment]
Your Idea sounds good, I'll bring UIs (Forms) to theSpawn in the 1.5.0 update of theSpawn.
Users can activate Forms and unactivate them, the forms will be for homes and warps.

**Comment by supercrafter333** [comment]
Done in V1.5.0-Dev! Thanks you!
