### ISSUE TITLE
[BUG:] Internal server error

### ISSUE THREAD

**Issue by rokibot009** [supercrafter333/theSpawn#27]
# Bug: [Bug Name]

### Informations
theSpawn Version: 1.4.2-3
PHP Version: 8.0
PocketMine-MP Version: 3.25.0

### Error

2021-10-31 [11:56:04] [Server thread/CRITICAL]: TypeError: "Cannot assign null to property supercrafter333\theSpawn\Others\TpaInfo::$tpa of type array" (EXCEPTION) in "plugins/theSpawn.phar/src/supercrafter333/theSpawn/Others/TpaInfo" at line 28
--
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #0 plugins/theSpawn.phar/src/supercrafter333/theSpawn/theSpawn(313): supercrafter333\theSpawn\Others\TpaInfo->__construct(string[9] KiOriiiii)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #1 plugins/theSpawn.phar/src/supercrafter333/theSpawn/Commands/TpacceptCommand(59): supercrafter333\theSpawn\theSpawn->hasTpaOf(string[13] MEMBASMI_WIBU, string[9] KiOriiiii)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/command/SimpleCommandMap(248): supercrafter333\theSpawn\Commands\TpacceptCommand->execute(object JackMD\NameSpaceRemover\CustomPlayer, string[8] tpaccept, array[1])
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/Server(1809): pocketmine\command\SimpleCommandMap->dispatch(object JackMD\NameSpaceRemover\CustomPlayer, string[22] tpaccept MEMBASMI_WIBU)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Player(2351): pocketmine\Server->dispatchCommand(object JackMD\NameSpaceRemover\CustomPlayer, string[22] tpaccept MEMBASMI_WIBU)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(239): pocketmine\Player->chat(string[23] /tpaccept MEMBASMI_WIBU)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/Player(3323): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #12 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 114.5.212.101 24142, object raklib\protocol\EncapsulatedPacket, integer 0)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1635656164.3121)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #18 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #19 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #20 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[8] /server/, string[16] /server/plugins/)
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #21 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
  | 2021-10-31 [11:56:04] [Server thread/CRITICAL]: #22 pmsrc(11): require(string[56] phar:///server/server.phar/src/pocketmine/PocketMine.php)

**Comment by supercrafter333** [comment]
Fixed in commit [f43cdc8](https://github.com/supercrafter333/theSpawn/commit/f43cdc8e60400b795154d60986954c03988e177e)
