### ISSUE TITLE
How to sethub proxy server

### ISSUE THREAD

**Issue by azhimmanru** [supercrafter333/theSpawn#29]
How to set hub proxy to server lobby
Waterdog proxy

**Comment by supercrafter333** [comment]
https://github.com/supercrafter333/theSpawn/blob/V1.5.2/resources/config.yml#L2-L4
1. Set `use-hub-server` to true.
2. Set your Proxy-IP to `hub-server-ip`
3. Set your Proxy-Port to `hub-server-port`
