### ISSUE TITLE
[BUG:] Language Folder is empty

### ISSUE THREAD

**Issue by MonoAdrian23** [supercrafter333/theSpawn#30]
# Bug: [Bug Name]

### Informations
theSpawn Version: [1.5.4]
Server-OS: [Linux Debian 10 Buster]
PHP Version: [8.0.12]
PocketMine-MP Version: [4.0.3]

### Error
[Console Error:]

### readjustment instructions
[I've done...]
[1. I have Changed the Language to German
[2. The Language Folder is still empty
[3. I dont know its a Bug?
[4. I need to Change Command Description and others.

### fix suggestions [optional]
[Your suggestion]

**Comment by supercrafter333** [comment]
That isn't a bug. The language folder will only contain any file if you set your language to `CUSTOM`.
[See more here](https://github.com/supercrafter333/theSpawn/blob/598cc591317586e2c3212523ea049c8e64e5e145/resources/config.yml#L48)

**Comment by MonoAdrian23** [comment]
Ah great thank you

**Comment by supercrafter333** [comment]
Kein Ding :)

**Comment by MonoAdrian23** [comment]
Hast du noch ein Tipp?
Es bleibt dennoch leer obwohl ich es auf CUSTOM gesetzt hab.

**Comment by supercrafter333** [comment]
Ich habe es gerade mal ausprobiert. Bei mir klappt alles... Nutzt du auch wirklich die neuste Version?

**Comment by MonoAdrian23** [comment]
Ja die letzte Dev Build

In Pocketmine 4.0.3

Ich hab Mal probiert den Languages Ordner zu löschen aber der wird auch nicht neu erstellt.

**Comment by MonoAdrian23** [comment]
Es hat nun nach 30 Minuten geklappt.

Geiles Plugin!
Weiter so 🥰

**Comment by supercrafter333** [comment]
😂
Freut mich und vielen Dank :)

**Comment by MonoAdrian23** [comment]
Ich will dir absolut nicht auf den Sack gehen und das ist gerade komplett themenfrei.
Aber kennst du zufällig ein Economy Plugin oder Scoreboard Plugin für die API 4?
Ich bin auf Pocketmine gewechselt und bin voller Begeisterung.

**Comment by supercrafter333** [comment]
Economy API habe ich selbst auf PM4 umprogrammiert, Poggit hat meine Pull-Request sogar schon gemerged. Wenn du möchtest kannst du mir auch gern auf Discord schreiben (`supercrafter333#4062`) oder meinem Development Discord joinen ([JOIN](https://discord.gg/ca6cWPpERp)).

**Comment by MonoAdrian23** [comment]
Ich nutze aktuell kein Discord.
Ich warte dann einfach ab bis etwas released wird.
Aber danke dir trotzdem

**Comment by supercrafter333** [comment]
EconomyAPI wird nicht mehr auf Poggit released.

**Comment by supercrafter333** [comment]
https://github.com/poggit-orphanage/EconomyS
Poggit hat meine Pull-Request bereits in EconomyAPI gemerged, weshalb du direkt das nutzen kannst.

**Comment by MonoAdrian23** [comment]
Boah du bist Mega.
Nur wegen dir hab ich extra auf Pocketmine gewechselt.
Ich danke dir wirklich von ganzem Herzen!

**Comment by supercrafter333** [comment]
xD Dankesehr

**Comment by MonoAdrian23** [comment]
Ich bin da Recht frisch was Pocketmine angeht

Bin halt von einer anderen Software hierher gewechselt.
Wie kann man das nutzbar machen.
Pocketmine 4 scheint etwas komplizierter zu sein als die 3

**Comment by MonoAdrian23** [comment]
Hat sich erledigt.
Ich hab was vom 4.12 entdeckt.
Wird wohl das sein.
Jetzt kannst du deinen Feierabend genießen 🤯

**Comment by supercrafter333** [comment]
Aber eine Frage hätte ich...
Wieso hattest du Müll über mich geredet mit jemand anderem auf einem Discord auf dem ich nicht einmal drauf war?

**Comment by MonoAdrian23** [comment]
Welcher andere war das denn?

**Comment by supercrafter333** [comment]
conwex

**Comment by MonoAdrian23** [comment]
Vergiss das einfach.
Davon hab ich mich getrennt.

**Comment by MonoAdrian23** [comment]
Aber ich brauche nochmal deine Hilfe
Wenn du magst.
Ich kriege einen Token Error.

Scheint aber alles korrekt zu sein.

Error: yaml_parse(): scanning error encountered during parsing: found character that cannot start any token (line 33, column 33), context while scanning for the next token (line 33, column 33)
File: pmsrc/src/utils/Config
Line: 180
Type: ErrorException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: EconomyAPI

Code:

Backtrace:
#0 (): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[185] yaml_parse(): scanning error encountered during parsing: found character that ca, string[59] phar:///home/minecraft/pocketmine.phar/src/utils/Config.php, integer 180)
#1 pmsrc/src/utils/Config(180): yaml_parse(string[2316] ---.language: en.commands:.  mymoney:.    usage: /mymoney.    description: &4Zei)
#2 pmsrc/src/utils/Config(119): pocketmine\utils\Config->load(string[51] /home/minecraft/plugin_data/EconomyAPI/messages.yml, integer 2, array[28])
#3 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(486): pocketmine\utils\Config->__construct(string[51] /home/minecraft/plugin_data/EconomyAPI/messages.yml, integer 2, array[28])
#4 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(428): onebone\economyapi\EconomyAPI->initializeLanguage()
#5 plugins/EconomyAPI.phar/src/onebone/economyapi/EconomyAPI(334): onebone\economyapi\EconomyAPI->initialize()
#6 pmsrc/src/plugin/PluginBase(137): onebone\economyapi\EconomyAPI->onEnable()
#7 pmsrc/src/plugin/PluginManager(438): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#8 pmsrc/src/Server(1383): pocketmine\plugin\PluginManager->enablePlugin(object onebone\economyapi\EconomyAPI#23718)
#9 pmsrc/src/Server(1009): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#23428)
#10 pmsrc/src/PocketMine(303): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#11 pmsrc/src/PocketMine(326): pocketmine\server()
#12 pmsrc(11): require(string[57] phar:///home/minecraft/pocketmine.phar/src/PocketMine.php)

PocketMine-MP version: 4.0.3 [Protocol 475]
Git commit: 795ebd182461f96beeb47b067f7fe33e76bc9059
uname -a: Linux d2779e7c13f3 5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64
PHP Version: 8.0.13
Zend version: 4.0.13
OS: Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.5.0+bedrock-1.18.0@482c679aa5ed0b81c088c2b1ff0b8110a94c8a6c
- pocketmine/bedrock-protocol 7.1.0+bedrock-1.18.0@42f2a00634c17c346fd98c05b2daf29d1fbf5805
- pocketmine/binaryutils 0.2.3@dc94786fc6c30012b1892f548dbb8a8c9c0a8cd9
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.3.0@ec742b209e8056bbe855069c4eff94c9734ea19b
- pocketmine/locale-data 2.2.0@dc88ad618a482e55b7c9fec162257efa62a67d6f
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.0.3@795ebd182461f96beeb47b067f7fe33e76bc9059
- pocketmine/raklib 0.14.2@e3a861187470e1facc6625040128f447ebbcbaec
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.23.0@46cd95797e9df938fdd2b03693b5fca5e64b01ce
- symfony/polyfill-php80 v1.23.1@1100343ed1a92e3a38f9ae122fc0eb21602547be
- symfony/polyfill-php81 v1.23.0@e66119f3de95efc359483f810c4c3e6436279436
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util

**Comment by supercrafter333** [comment]
Der Error gehört nicht hier rein. Hat nichts mit theSpawn zutun.

**Comment by MonoAdrian23** [comment]
Oh upsi.
Sorry

**Comment by MonoAdrian23** [comment]
Ich hoffe das passt jetzt so.
Ich wünsche dir erstmal einen Schönen Abend und hoffe das ich dir nicht zu sehr auf den Sack ging

**Comment by supercrafter333** [comment]
Alles gut. Dir auch :)
