### ISSUE TITLE
thought 

### ISSUE THREAD

**Issue by DimonYoing** [supercrafter333/theSpawn#31]
Add to be able to put an icon in /warp.

**Comment by DimonYoing** [comment]
Make a list of SELECT houses in /home List of houses will not work. It is conla that you click on the list, a choice of houses appears where to teleport

**Comment by DimonYoing** [comment]
Так сделайте чтобы можно было изменить текст кнопки "Send"

**Comment by supercrafter333** [comment]
> Так сделайте чтобы можно было изменить текст кнопки "Send"

1st - Please write in english!!
2nd - I can't do that because pocketmine doesn't have any function for that.

**Comment by DimonYoing** [comment]
You can change the text of the button in the UI form, like the value

**Comment by DimonYoing** [comment]
Just add an exit button and remove the main one or it will automatically be removed

**Comment by DimonYoing** [comment]
Так в таких плагинах обычно ставят иконки для /warp в pocketmine

**Comment by DimonYoing** [comment]
So in such plugins they usually put icons in / warp in pocketmine

**Comment by DimonYoing** [comment]
I thought you could implement it

**Comment by DimonYoing** [comment]
And in home, you could simply select houses in the home list

**Comment by DimonYoing** [comment]
I can send you an example screenshot

**Comment by supercrafter333** [comment]
Yes, please send me a screenshot.

**Comment by supercrafter333** [comment]
> > Так сделайте чтобы можно было изменить текст кнопки "Send"
> 
> 1st - Please write in english!! 2nd - I can't do that because pocketmine doesn't have any function for that.

https://forums.pmmp.io/threads/how-do-you-change-the-submit-button-to-another-text.5103/

**Comment by DimonYoing** [comment]
![2022_02_13_12 06 41](https://user-images.githubusercontent.com/98219533/153742909-1bb97c79-56f5-414c-91de-7d4cc2a043ec.jpg)

**Comment by DimonYoing** [comment]
this screenshot shows icons in /warp

**Comment by DimonYoing** [comment]
but only so that you can add icon there yourself

**Comment by supercrafter333** [comment]
Done in [ef17d31](https://github.com/supercrafter333/theSpawn/commit/ef17d314a07d6b10b638fdbe57c90be2da6897cb)
