### ISSUE TITLE
[Suggestion:] Save the position in which you look when using commands

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#33]
In the old MSpawns plugin when you used /sethub or /setlobby, apart from saving the block location, it saved the position in which the body appeared, i.e. if I used the command looking at a statue, the players when joining them appeared looking at the statue.

It is very useful for servers that only have one path to follow, but if you appear with your back to the spawn it looks a bit weird.

I would also like this to apply to other commands such as /warp or /home.

Here is the line of code that I believe is responsible for that in the MSpawns plugin:
```php
$this->plugin->setHub($sender->getLevel(), $sender->getX(), $sender->getY(), $sender->getZ(), $sender->getYaw(), $sender->getPitch());
```
I'm not sure if it's that line, here is the direct link to the code
https://github.com/EvolSoft/MSpawns/blob/master/src/MSpawns/Commands/SetHub.php

**Comment by supercrafter333** [comment]
I'll implement that soon.

**Comment by supercrafter333** [comment]
❗ - The changes to implement this will break the API backward compatiblity.

**Comment by supercrafter333** [comment]
Done in [0cb15e9](https://github.com/supercrafter333/theSpawn/commit/0cb15e9130cb4154730f5c2f2e9b85054294ceca)

**Comment by supercrafter333** [comment]
I would be very happy if you join my discord server:
### Join the community
[![Discord Banner](https://discordapp.com/api/guilds/847099444465238036/widget.png?style=banner3)](https://discord.gg/ca6cWPpERp)
