### ISSUE TITLE
[Suggestion:] New command /editwarp

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#35]
**Is your feature request related to a problem? Please describe.**
I have been thinking that it would be great to add a command to edit the warps, It could have a UI interface and the following options would be shown:

- Change the warp name
- Change the warp image
- Update the warp location
- Change the warp permission
- Remove the warp permission

It can be useful in case you don't like the image you have placed, so you don't have to delete it and create another warp, or to change the name if you got confused or also if you want to delete or change the warp permission etc.

**Describe the solution you'd like**
X

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by supercrafter333** [comment]
Done!
