### ISSUE TITLE
[Suggestion:] hub-teleport-on-death

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#39]
**Is your feature request related to a problem? Please describe.**
I've been thinking that maybe some of you would prefer that when players die, instead of going to the world spawn, they could choose the option to return to the Hub.

You could put the option in the config.yml to enable or disable it.
```yml
#hub teleport on death [true | false]
hub-teleport-on-death: "true"
```

**Describe the solution you'd like**
X

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by supercrafter333** [comment]
Done! Tests for theSpawn v1.8.0-dev will begin tomorrow.
