### ISSUE TITLE
[Suggestion:] Add autocomplete in /tpa

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#42]
**Is your feature request related to a problem? Please describe.**
When a user tries to use /tpa Ste what the plugin does is to see if there is someone called "Ste" on the server

**Describe the solution you'd like**
Add autocomplete, i.e. if I put /tpa Ste, the plugin will look for a player whose name continues with "Ste" and then ask tpa to "Steve" without having to add his whole name.

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by supercrafter333** [comment]
Already implemented.

**Comment by MrBlasyMSK** [comment]
> Already implemented.

no its not

**Comment by MrBlasyMSK** [comment]
Oh, I noticed that you have to write exactly the same name at the beginning, if you write it in lower or upper case it is no good.
