### ISSUE TITLE
when enabled spawnDelay and then go anand then useand thand then go to use the command in the server causing the server to go down

### ISSUE THREAD

**Issue by ATLK00** [supercrafter333/theSpawn#44]
# Bug: [Bug Name]

### Informations
theSpawn Version: [1.6.0]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [8.0.12]
PocketMine-MP Version: [4.0.0]

### Error
[Console Error:]

### readjustment instructions
[I've done...]
[1. ...]
[2. ...]
[3. ...]

### fix suggestions [optional]
[Your suggestion]

**Comment by supercrafter333** [comment]
Please fill out the version-informations and send the error!

**Comment by supercrafter333** [comment]
Closed due to lack of information.
