### ISSUE TITLE
[BUG:] You can teleport to your home but you get an error saying that it was not possible.

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#45]
# Bug: You can teleport to your home but you get an error saying that it was not possible.

### Informations
theSpawn Version: [1.8.0-dev]
Server-OS: [linux]
PHP Version: [8.0.17]
PocketMine-MP Version: [4.2.6]

### Error
https://streamable.com/dbfm17

### readjustment instructions
[I've done...]
[1. Create a home]
[2. Use the home]
[3. If you are "lucky" you will get the message the teleport was cancelled]

### fix suggestions [optional]
X

**Comment by supercrafter333** [comment]
I know about some bugs like that. That's the reason while that's a beta-feature.

**Comment by supercrafter333** [comment]
Can you test the newest build, please?
