### ISSUE TITLE
[Suggestion:] Do not change the position in the UI table when editing a home

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#47]
**Is your feature request related to a problem? Please describe.**
I have seen that in the new version when I use /edithome and change some parameter like rename or set new home point, in the UI interface the home is updated too. For example, if I edit my first home called "MyFirstHome" and rename it to "MySuperFirstHome" the home will be placed in the 2nd place of the UI interface when using /home.
I don't think this happens with warp, and if it does, I would like it to stay in the same position.

**Describe the solution you'd like**
Simply do not change the position of the house when update
**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by supercrafter333** [comment]
The array will be edited. This cannot be fixed without large API changes in theSpawn.
