### ISSUE TITLE
[Suggestion:] Add option to use /tpaccep or /tpdeny if only 1 application is pending

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#51]
**Is your feature request related to a problem? Please describe.**
I have been testing the `/tpa` commands and have seen that you have to always put the full name of the person for tpa to be able to be done, but only having 1 tpa request it is a bit absurd to have to use the full name instead of just accepting it.
This would save a lot of time for players so they don't have to type the full name of the other person.

**Describe the solution you'd like**
X

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by supercrafter333** [comment]
this would only result in performance loss with the current TPA API.
