### ISSUE TITLE
[Suggestion:] NAME

### ISSUE THREAD

**Issue by Tuvqlu** [supercrafter333/theSpawn#54]
**Is your feature request related to a problem? 
YES
Please describe.**
EX. Im always frustrated when I do /hub and this weird message with a prefix and message I don’t like

**Describe the solution you'd like**
The ability to change the prefix and message

**Describe alternatives you've considered**
1. Deleting the plugin 2. 
Trying other plugins
3. Crying 
**Additional context**
I can’t see this meaaage anymore pls fix

**Comment by supercrafter333** [comment]
Just use custom messages. You can choose `CUSTOM` as [`language`](https://github.com/supercrafter333/theSpawn/blob/master/resources/config.yml#L53-L63) in your `config.yml` file of theSpawn.
