### ISSUE TITLE
[Suggestion:] Add option to see the number of people in the world when using /warp

### ISSUE THREAD

**Issue by MrBlasyMSK** [supercrafter333/theSpawn#57]
I thought it would be great if there was an option in the config that you could enable and remove the "click here to go to warp" message as it is a bit useless and people should know how to do it and add something like `"8 players in this world"` or `"8 players in this warp"` is just an example

And I say to remove the "click to go to warp" because if you add this maybe it would be a little small and that there is so much information is not good, plus I do not see it so useful either

**Comment by supercrafter333** [comment]
Omg! I really like your idea. That would be a part of the next theSpawn update. <3

**Comment by supercrafter333** [comment]
Added to the PM5-milestone.
