### ISSUE TITLE
⭐️ » Feature

### ISSUE THREAD

**Issue by DevTIG3535** [supercrafter333/theSpawn#58]
I have a suggestion that you spawn at your last position.

By this I mean that as soon as you leave the server at one point and have joined again, spawn again exactly at this point.

**Comment by supercrafter333** [comment]
I thought you mean that if a player dies/respawn that he will be teleported to his last position xD

Just set [`hub-teleport-on-join`](https://github.com/supercrafter333/theSpawn/blob/master/resources/config.yml#L32) to `false`.
