### ISSUE TITLE
[Suggestion:] PlayerWarp

### ISSUE THREAD

**Issue by AraaCuteUwU** [supercrafter333/theSpawn#59]
Can you add /playerwarp command?

**Comment by supercrafter333** [comment]
What should this command do?

**Comment by AraaCuteUwU** [comment]
Like warp but can used by member (not op)

**Comment by supercrafter333** [comment]
Added to the [`PM5 / v2`](https://github.com/supercrafter333/theSpawn/milestone/2) milestone.

**Comment by supercrafter333** [comment]
Please give some more descriptions.

**Comment by supercrafter333** [comment]
Added in v2.0.0-dev5 ([`PM5-development`-branch](https://github.com/supercrafter333/theSpawn/tree/PM5-development)).
