### ISSUE TITLE
Force Closed BUG

### ISSUE THREAD

**Issue by SrathYT** [supercrafter333/theSpawn#61]
# Bug: [Force Shut down]

### Informations
theSpawn Version: [1.6.0]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [8.0.12]
PocketMine-MP Version: [4.0.0]

### Error
[Join Error:]

### readjustment instructions
[I've done...]
[1. I starting it's ok but...]
[2. I join my server her and server closed...]
[3. ...]

### fix suggestions [optional]
I'M so angry😡

**Comment by SrathYT** [comment]
![Uploading Screenshot_2022-07-03-17-11-23-74_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by supercrafter333** [comment]
U angry? Okay, I won't be stressed. You can definitely wait a little longer. ^^

**Comment by supercrafter333** [comment]
Your screenshot isn't loading and you didn't give me enought information. I can't help you.

**Comment by SrathYT** [comment]
You mean?

**Comment by SrathYT** [comment]
I will show

**Comment by supercrafter333** [comment]
Please send me an error. I can't help you so.

**Comment by supercrafter333** [comment]
![image](https://user-images.githubusercontent.com/53967726/177037603-e2a91320-f9d1-47e5-932a-50d0762b6781.png)

**Comment by SrathYT** [comment]
Scroll up^

**Comment by supercrafter333** [comment]
Closed due to lack of information.
