### ISSUE TITLE
[BUG:] Description...

### ISSUE THREAD

**Issue by YT-Duckyyy** [supercrafter333/theSpawn#63]
# Bug: [Bug Name]

### Informations
theSpawn Version: [1.6.0]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [8.0.12]
PocketMine-MP Version: [4.0.0]

### Error
[Console Error:]
[20:25:42.800] [Server thread/CRITICAL]: ErrorException: "Undefined array key "task"" (EXCEPTION) in "plugins/theSpawn.phar/src/supercrafter333/theSpawn/theSpawn" at line 1220
--- Stack trace ---
  #0 plugins/theSpawn.phar/src/supercrafter333/theSpawn/theSpawn(1220): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[26] Undefined array key "task", string[86] phar:///home/container/plugins/theSpawn.phar/src/supercrafter333/theSpawn/theSpa, int 1220)
  #1 plugins/theSpawn.phar/src/supercrafter333/theSpawn/EventListener(32): supercrafter333\theSpawn\theSpawn->stopSpawnDelay(object UnknownNull\SpaceRemover\CustomPlayer#123112)
  #2 pmsrc/src/event/RegisteredListener(60): supercrafter333\theSpawn\EventListener->onMove(object pocketmine\event\player\PlayerMoveEvent#149412)
  #3 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#149412)
  #4 pmsrc/src/player/Player(1240): pocketmine\event\Event->call()
  #5 pmsrc/src/player/Player(1327): pocketmine\player\Player->processMostRecentMovements()
  #6 pmsrc/src/world/World(842): pocketmine\player\Player->onUpdate(int 224311)
  #7 pmsrc/src/world/World(768): pocketmine\world\World->actuallyDoTick(int 224311)
  #8 pmsrc/src/world/WorldManager(348): pocketmine\world\World->doTick(int 224311)
  #9 pmsrc/src/Server(1818): pocketmine\world\WorldManager->tick(int 224311)
  #10 pmsrc/src/Server(1700): pocketmine\Server->tick()
  #11 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #12 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #13 pmsrc/src/PocketMine(328): pocketmine\server()
  #14 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

### readjustment instructions
[I've done...]
/spawn once ive set one

### fix suggestions [optional]
[Your suggestion]

**Comment by supercrafter333** [comment]
Please use the newest version of theSpawn.
