### ISSUE TITLE
[BUG:] Description...

### ISSUE THREAD

**Issue by MrJultz** [supercrafter333/theSpawn#65]
# Bug: [Error changing language]

### Informations
theSpawn Version: [1.8.3]
Server-OS: [Linux]
PHP Version: [8.0.13]
PocketMine-MP Version: [4.10.0]

### Error
[Console Error:
PocketMine-MP Crash Dump Sat Nov 19 14:34:48 MSK 2022

PocketMine-MP version: 4.10.0 [Protocol 557]
Git commit: 0d5287bf0bd7138113e1c154d3c3a3b83a407d82
PHP version: 8.0.13
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: theSpawn

Error: Failed to parse config /home/plugins/theSpawn/Languages/messages.yml: yaml_parse(): parsing error encountered during parsing: did not find expected key (line 162, column 23), context while parsing a block mapping (line 4, column 1)
File: pmsrc/src/utils/ConfigLoadException
Line: 29
Type: pocketmine\utils\ConfigLoadException
Backtrace:
#0 pmsrc/src/utils/Config(184): pocketmine\utils\ConfigLoadException::wrap(string[45] /home/plugins/theSpawn/Languages/messages.yml, object ErrorException#978938)
#1 pmsrc/src/utils/Config(117): pocketmine\utils\Config->load(string[45] /home/plugins/theSpawn/Languages/messages.yml, int 2, array[0])
#2 plugins/theSpawn (2).phar/src/supercrafter333/theSpawn/MsgMgr(53): pocketmine\utils\Config->__construct(string[45] /home/plugins/theSpawn/Languages/messages.yml, int 2)
#3 plugins/theSpawn (2).phar/src/supercrafter333/theSpawn/theSpawn(228): supercrafter333\theSpawn\MsgMgr::getMsgs()
#4 plugins/theSpawn (2).phar/src/supercrafter333/theSpawn/theSpawn(265): supercrafter333\theSpawn\theSpawn->getMsgCfg()
#5 plugins/theSpawn (2).phar/src/supercrafter333/theSpawn/theSpawn(151): supercrafter333\theSpawn\theSpawn->versionCheck(string[5] 1.8.3, false)
#6 pmsrc/src/plugin/PluginBase(117): supercrafter333\theSpawn\theSpawn->onEnable()
#7 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#8 pmsrc/src/Server(1421): pocketmine\plugin\PluginManager->enablePlugin(object supercrafter333\theSpawn\theSpawn#22320)
#9 pmsrc/src/Server(1026): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21912)
#10 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[6] /home/, string[14] /home/plugins/)
#11 pmsrc/src/PocketMine(328): pocketmine\server()
#12 pmsrc(11): require(string[50] phar:///home/PocketMine-MP.phar/src/PocketMine.php)

Code:
[20]  */
[21] 
[22] declare(strict_types=1);
[23] 
[24] namespace pocketmine\utils;
[25] 
[26] final class ConfigLoadException extends \RuntimeException{
[27] 
[28] 	public static function wrap(string $fileName, \Exception $e) : self{
[29] 		return new self("Failed to parse config $fileName: " . $e->getMessage(), 0, $e);
[30] 	}
[31] }
]

### fix suggestions [optional]
[After changing to Russian, the plugin stopped working when half of the config was changed to Russian, it was still functioning, and after a complete change - an error]

**Comment by supercrafter333** [comment]
That isn't a bug of theSpawn. You did something wrong in your messages.yml. PHP und PMMP can only parse the file if everything is in the correct format. Please check line 162 in your messages.yml file.
