### ISSUE TITLE
[BUG:] Crash when on delay spawn, then /spawn again in second.

### ISSUE THREAD

**Issue by husencoolwolf** [supercrafter333/theSpawn#66]
# Bug: [Undefined array key "task"]

### Informations
theSpawn Version: [1.8.3]
Server-OS: [Linux, android]
PHP Version: [8.0.25]
PocketMine-MP Version: [4.12.1 [Protocol 560]]

### Error
[Console Error:Undefined array key "task"]

### readjustment instructions
[So i used /spawn then there delay notification. but i moved, so the spawn is canceled. But not too long its about 2-3 second later, i used /spawn again. Then the server crash leave crashdump]
[You can see my crashdump [crashdump](https://justpaste.it/9y0qy)]

**Comment by supercrafter333** [comment]
Will be fixes soon if it's valid.

**Comment by supercrafter333** [comment]
Confirmed! This bug will be fixed in the next hours.

**Comment by supercrafter333** [comment]
Fixed in v1.8.4

**Comment by husencoolwolf** [comment]
> Fixed in v1.8.4

Hey dude. sry. but i recently noticed it crash when counter finish too when /spawn. (i already /setspawn

**Comment by supercrafter333** [comment]
Please send the error.

**Comment by supercrafter333** [comment]
And it was fixed in v1.8.4
