### ISSUE TITLE
[Suggestion:] Cancel tpa / tpahere requests.

### ISSUE THREAD

**Issue by Endermanbugzjfc** [supercrafter333/theSpawn#68]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when not able to cancel tpa / tpahere requests.

After creating or accepting the received ones.

**Describe the solution you'd like**
Tpa / tpahere requests can be cancelled by moving around (with a threshold, not counting head movements, for example).
**Describe alternatives you've considered**
Or run command `/tpacancel` / `tpcancel`.

**Additional context**

**Comment by supercrafter333** [comment]
TPAs can alreary be declined/cancelled by using `/tpdecline`

**Comment by Endermanbugzjfc** [comment]
Thank you for telling me, I will try it out later.
