### ISSUE TITLE
[BUG:] On join not teleported to HUB

### ISSUE THREAD

**Issue by benda95280** [supercrafter333/theSpawn#7]
# Bug: On join not teleported to HUB

### Informations
PocketMine-MP Version: [3.19.0]

### Error
[Console Error:]
N/A

### readjustment instructions
Defined HUB
Teleport to a level
Exit
Join again, not spawning in HUB.

### fix suggestions [optional]
[Your suggestion]
I do not see part of code that should handle it

**Comment by supercrafter333** [comment]
This is not implemented.
