### ISSUE TITLE
[Suggestion:] /wild command

### ISSUE THREAD

**Issue by GH-PM** [supercrafter333/theSpawn#70]
**Is your feature request related to a problem? Please describe.**
In many survival worlds as you may know the spawn is often broken or there are practically not enough resources for new players and it can be a bit frustrating for them to have to walk so far

**Describe the solution you'd like**
I would like theSpawn to add the /wild command so that new players don't have to spend so much time walking around

**Describe alternatives you've considered**
x

**Additional context**
I know that currently there is already a plugin that has integrated the /wild command called "Wilderness" but I thought that this plugin could use to have it by default as it includes several commands such as /warp /tp and things related to teleportation to other sites.
Here are the things you could add:

- [ ] Chunk Load Flood Protection (A method to prevent players from constantly loading chunks unnecessarily)
- [ ] Safe Spawn (Prevents players from appearing in walls or underground)
- [ ] Permission Manager (You can control from the configuration whether you want them to have OP access, all or none)
- [ ] Custom Cooldown (Time required for player to teleport)
- [ ] Moving while teleporting (To be able to set or remove the option of letting the player move while using the /wild command)
- [ ] Command Cooldown (Being able to add a cooldown to avoid spam)
- [ ] Custom Alias (To be able to shorten the command to whatever you like)
- [ ] Banned Worlds (Ban the command on worlds where you don't want it to be used)
- [ ] Effect While TP (To grant you an effect when teleporting or while teleporting)
- [ ] Custom Sound (A custom sound while teleporting)
- [ ] Custom Particles (Customizable particles while teleporting)
- [ ] Economy Support (Add support for economy plugins in case you want to use the command to discount money to the player)

Obviously it is not necessary to add everything, I have only compiled what many people would like. Feel free to add whatever you like, if you don't like the idea of the command close this suggestion

**Comment by supercrafter333** [comment]
1. theSpawn isn't a vanilla-plugin. /wild won't be added.
2. Some suggested features are already added
3. theSpawn isn't a world-protection plugin. Please use WorldGuard or WorldProtect.

**Comment by GH-PM** [comment]
> 1. theSpawn isn't a vanilla-plugin. /wild won't be added.
> 2. Some suggested features are already added
> 3. theSpawn isn't a world-protection plugin. Please use WorldGuard or WorldProtect.

1. The /wild command is not vanilla, it does not exist neither in java nor in bedrock without any kind of plugin.
![image](https://user-images.githubusercontent.com/127597296/224484894-2e2c839c-e9bd-4f20-b86b-61390f5cd68a.png)
2. I mean specifically for the /wild command
3. I have not asked for any spawns protection plugin, I have asked for a plugin to teleport to another random place as this plugin has several teleportation commands such as /tpa /back /home etc
If you don't want to do it just say you are not interested, don't make excuses

**Comment by supercrafter333** [comment]
theSpawn won't implement the /wild command.
