### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by NdaruAjaa** [supercrafter333/theSpawn#71]
PocketMine-MP version: 4.15.3 [Protocol 567]
Git commit: 71e3e3652250130762110c63a2649b04865fc74c
PHP version: 8.0.27
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: theSpawn

Error: supercrafter333\theSpawn\theSpawn::isPositionSafe(): Argument #1 ($position) must be of type pocketmine\world\Position|pocketmine\entity\Location|false|null, string given, called in phar:///home/container/plugins/theSpawn_dev-174.phar/src/supercrafter333/theSpawn/Commands/HomeCommand.php on line 92
File: plugins/theSpawn_dev-174.phar/src/supercrafter333/theSpawn/theSpawn
Line: 1269

**Comment by supercrafter333** [comment]
Your world cannot be loaded or isn't existing. This isn't a important bug and won't be fixed. Please update your server to PM5 on 31.03.2023 and use theSpawn v2.0.0 on the PM5 server.
