### ISSUE TITLE
Bug class

### ISSUE THREAD

**Issue by LordFit** [supercrafter333/theSpawn#73]
# Bug: [cannot declare class because the name is already use]

### Informations
theSpawn Version: [2.0.0]
PocketMine-MP Version: [5.0.1]

### Error
`Fatal error: Cannot declare class supercrafter333\theSpawn\supercrafter333\theSpawn\libs\EasyUI\Form, because the name is already in use in phar://E:/LordFitra/PM5/plugins/theSpawn (2) (1).phar/src/libs/EasyUI/Form.php on line 17
`

**Comment by supercrafter333** [comment]
#75
