### ISSUE TITLE
This plugin PM4 not for PM5

### ISSUE THREAD

**Issue by MagmaZ3637** [supercrafter333/theSpawn#74]
# Bug: [Incompatible plugin]

### Informations
theSpawn Version: [1.6.0]
Server-OS: [Linux Ubuntu 20.04]
PHP Version: [8.0.12]
PocketMine-MP Version: [4.0.0]

### Error
[Console Error:]

### readjustment instructions
[I've done...]
[1. ...]
[2. ...]
[3. ...]

### fix suggestions [optional]
[Your suggestion]

**Comment by supercrafter333** [comment]
This plugin will no longer get updates for pm4! If you like to use the newest theSpawn version, use theSpawn v2.0.0 for PM5.

**Comment by supercrafter333** [comment]
Closed due to bad description.
