### ISSUE TITLE
E Compile Eror

### ISSUE THREAD

**Issue by MagmaZ3637** [supercrafter333/theSpawn#76]
Reason:
Error: Cannot declare class supercrafter333\theSpawn\supercrafter333\theSpawn\libs\EasyUI\Form, because the name is already in use
File: plugins/theSpawn.phar/src/libs/EasyUI/Form
Line: 17
Type: E_COMPILE_ERROR
I use plugin ver: 2.0.0-poggit

**Comment by supercrafter333** [comment]
I can confirm this. It's a poggit bug and I reported it to the poggit-team.

**Comment by trickalia** [comment]
i had same issue

**Comment by supercrafter333** [comment]
Fixed in the latest poggit-release of theSpawn. ([v2.0.1-poggit](https://poggit.pmmp.io/p/theSpawn/2.0.1-poggit))
