### ISSUE TITLE
[Suggestion:] warp

### ISSUE THREAD

**Issue by kingboydeve** [supercrafter333/theSpawn#79]
warp group
Like this:
/warpset addgroup <groupname> <warpcmd(an Independent cmd)>
/warpset add <group> <warpname>
/warpset addgroup

**Comment by kingboydeve** [comment]
Please first add for pm4.0.0 :{

**Comment by supercrafter333** [comment]
> warp group Like this: /warpset addgroup <warpcmd(an Independent cmd)> /warpset add /warpset addgroup

What should this feature exactly do? Please explain in more detail.

**Comment by supercrafter333** [comment]
> Please first add for pm4.0.0 :{

theSpawn is no longer under development for PM4. theSpawn will only get updates for PM5 and newer.

**Comment by kingboydeve** [comment]
Please back version :|

**Comment by kingboydeve** [comment]
Adds 
Like this:
/warp - opens default warps
I use this commands:
I add a warp group with customed command and permission 
I :
/vipwarps - if i have permission of this watp group opens another warpui

**Comment by supercrafter333** [comment]
I think that is (almost) exclusively your own wish/suggestions. I don't think this is needed.

**Comment by kingboydeve** [comment]
Make a Survey!

**Comment by supercrafter333** [comment]
No, that's my plugin. NOT yours.
