### ISSUE TITLE
[BUG:] Internal Server Error

### ISSUE THREAD

**Issue by Sureiyaaa** [supercrafter333/theSpawn#8]
Everytime I try to set a hub it will says Internal server error

**Comment by supercrafter333** [comment]
Hey,
Thanks for your bug-report. 

Can you Senf ne the Error, please?

**Comment by supercrafter333** [comment]
I'll fix it soon

**Comment by supercrafter333** [comment]
fixed in V1.2.4

**Comment by Sureiyaaa** [comment]
Thank you!
