### ISSUE TITLE
warp eror 5.3.0

### ISSUE THREAD

**Issue by ItzzYoshi** [supercrafter333/theSpawn#82]
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: theSpawn

Error: Call to a member function getName() on null
File: plugins/theSpawn.phar/src/form/WarpForms
Line: 43
Type: Error
Backtrace:
#0 plugins/theSpawn.phar/src/commands/warp/WarpCommand(51): supercrafter333\theSpawn\form\WarpForms->open(object pocketmine\player\Player#186497)
#1 pmsrc/src/command/SimpleCommandMap(212): supercrafter333\theSpawn\commands\warp\WarpCommand->execute(object pocketmine\player\Player#186497, string[4] warp, array[0])
#2 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object

**Comment by supercrafter333** [comment]
Looks like your warp-config-file is corrupted. This shouldn't be a bug of theSpawn.
