### ISSUE TITLE
[BUG:] World Name on lower case

### ISSUE THREAD

**Issue by Sureiyaaa** [supercrafter333/theSpawn#9]
The new version 1.2.4 is working for me but I hope the setting of the world name is fixed when I checked the theHub.yml I saw that the world name is on lowercase (spawn). my original world name was on capital S (Spawn) I think it's not gonna work for some people who has a capital letter on their worlds.

**Comment by supercrafter333** [comment]
It works in all of my Servers. Please Test it before you open an Issue.
